before_install:
  - gem install bundler
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
branches:
  only:
    - master
notifications:
  email:
    recipients:
       - lawrence.pit@gmail.com
    on_success: change
    on_failure: always
